### ISSUE TITLE
Support for SQL Alchemy 2.0

### ISSUE THREAD

**Issue by bryanterichardson** [MacHu-GWU/sqlalchemy_mate-project#4]
It seems some of your heavily used packages (`uszipcodes` for example) depend on this package for support. While those packages may support SQL Alchemy 2.0, their dependency on this prevents SQL Alchemy 2.0 from actually being used. This project specifies a requirement of `sqlalchemy<2`. Could we update that? Thank you in advance!

**Comment by MacHu-GWU** [comment]
Hi @bryanterichardson maintaining sqlalchemy 1.0 and 2.0 compatibility is really really hard. That's why the sqlachemy_mate version number are aligned with compatible sqlalchemy.

Since sqlalchemy 2.X now becomes stable, I am adding 2.0 support soon (within a week). I want to make sure all syntax are 2.0 compatible (no longer 1.X compatible) So people can either use sqlalchemy_mate<2.0.0 or sqlalchemy_mate>=2.0.0

**Comment by MacHu-GWU** [comment]
Release [2.0.0.0](https://pypi.org/project/sqlalchemy-mate/2.0.0.0/)
